<a href="https://colab.research.google.com/github/bassamadnan/tf-fundamentals/blob/main/TensorFlowFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensorflow Fundamentals
To be covered:
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and NumPy
- Using @tf.function (speed up regular py functions)
- Using GPUs with TensorFlow (TPUs)


In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
# Create tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check for dimensions of a tensor (ndim)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [5]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)

In [6]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]
                              ], dtype=tf.float16)
another_matrix, another_matrix.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 3.,  2.],
        [ 8.,  9.]], dtype=float16)>, 2)

In [7]:
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor, tensor.ndim


(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>, 3)

# Creating tensors with tf.Variable

In [8]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [9]:
# below gives error
# changeable_tensor[0] = 7
# try instead
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Random Tensors with TensorFlow
After numerically encoding, initially , the tensor is initialized with random weights (random tensor). It then tweaks these random weights till it starts desired results.

In [10]:
# Create random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2)) # taken from normal distribution
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

# Shuffle a tensor (used to remove influence of inherent order)

In [11]:
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
tf.random.shuffle(not_shuffled, seed=42) # Randomly shuffles a tensor along its first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [12]:
tf.random.set_seed(42) # Global level seed 
tf.random.shuffle(not_shuffled, seed=42) # operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

TODO: https://www.tensorflow.org/api_docs/python/tf/random/set_seed

# Turning NumPy arrays into tensors
The main difference between a array and a tensor is that tensors can be run on GPUs

In [13]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [14]:
B = tf.constant(numpy_A, shape=(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Important attributes 
- **Shape** -The length (number of elements) of each of the dimensions of a tensor. (tensor.shape)
- **Rank**- The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n. (tensor.ndim)
- **Axis** or **Dimension** - A particular dimension of a tensor.(tensor[0], tensor[:,1]..)
- **Size** The total number of items in the tensor (tf.size(tensor))

In [15]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [16]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [17]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [18]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])


In [19]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [20]:
#Alter to above
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Manipulating Tensors
Basic operations: 

`+`, `-`, `*`, `/`

In [21]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [22]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [23]:
tensor*10 
# alternatively tf.math. can be used for speeding up

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [24]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [26]:
tensor @ tensor # Dot product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [31]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [32]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [33]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [35]:
tf.tensordot(tf.transpose(X), Y, axes=1) # on the first axis

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [36]:
# Change from int32 to float32
C = tf.constant([1, 7])
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

## Aggregating Tensors
Condensing tensors from multiple values down to a smaller ammount of values
The methods typically have syntax `reduce()_[action]`
- `tf.abs(tensor)` - computes the absolute value of the tensor 
- `tf.reduce_min()` - find minimum value in a tensor
- `tf.reduce_max()` - find max value in a tensor  (eg -highest prediction probability).
- `tf.reduce_sum()`- find the sum of all elements in a tensor

TODO - Using above methods find Standard Deviation and Variance ✅


In [37]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([21, 44, 89, 70, 44, 23, 28, 68, 12, 56, 88, 40, 35, 41, 82, 78, 99,
       92, 18, 93, 55, 32, 52, 94, 72, 74, 92, 51, 55, 43, 87, 48,  5, 88,
       37, 94,  3, 18, 96, 16, 72, 69, 79, 93,  3, 48, 11, 18,  9,  9])>

In [39]:
tf.abs(E)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([21, 44, 89, 70, 44, 23, 28, 68, 12, 56, 88, 40, 35, 41, 82, 78, 99,
       92, 18, 93, 55, 32, 52, 94, 72, 74, 92, 51, 55, 43, 87, 48,  5, 88,
       37, 94,  3, 18, 96, 16, 72, 69, 79, 93,  3, 48, 11, 18,  9,  9])>

In [41]:
tf.reduce_min(E), tf.reduce_max(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=3>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2644>)

In [48]:
import tensorflow_probability as tfp
# tfp.math.reduce_std(E) ... wont work with dtype int
tfp.stats.variance(E) 

<tf.Tensor: shape=(), dtype=int64, numpy=929>

In [49]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.472048>

## Find positional minimum and maximum of a tensor 

In [51]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.59313431, 0.4019522 , 0.66025411, 0.58536889, 0.98452245,
       0.37036545, 0.47834377, 0.43172859, 0.44175987, 0.26048644,
       0.72637869, 0.00639989, 0.8913745 , 0.51236676, 0.59711728,
       0.78891057, 0.29289489, 0.90912652, 0.43912295, 0.17909767,
       0.07886141, 0.75755827, 0.50846194, 0.92838028, 0.0319196 ,
       0.72919981, 0.40507518, 0.14453547, 0.98027987, 0.88369946,
       0.15897929, 0.74348481, 0.42816398, 0.20635077, 0.45911053,
       0.53156738, 0.3535031 , 0.46812635, 0.1590361 , 0.30084965,
       0.52855435, 0.78403593, 0.19579857, 0.00811099, 0.43053255,
       0.96770382, 0.33254045, 0.94313722, 0.58677952, 0.26666305])>

In [52]:
tf.argmax(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=int64, numpy=11>)

In [53]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## Squeezing a tensor (removing all single dimensions)

In [54]:
tf.random.set_seed(42)
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))

In [55]:
G_squeeze = tf.squeeze(G)

In [56]:
G.shape, G.ndim, G_squeeze.shape, G_squeeze.ndim 

(TensorShape([1, 1, 1, 1, 50]), 5, TensorShape([50]), 1)

# One-Hot Encoding

In [57]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [58]:
# tf.sqrt, tf.math.log needs to be FLOAT

In [1]:
!nvidia-smi

Mon Oct  3 13:50:04 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
# Finding access to GPUs
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]